CREATE TABLE IF NOT EXISTS items(
    id SERIAL PRIMARY KEY,
    itemname VARCHAR(255) NOT NULL,
    itemcategory VARCHAR(255) NOT NULL,
    amount INTEGER NOT NULL DEFAULT '1',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);